<a href="https://colab.research.google.com/github/devincriniti/DSC_110/blob/main/Data_Cleaning_%26_Summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## we are importing the pre installed pandas library and naming it "pd"
import pandas as pd

In [4]:
## we are reading the csv file and naming it "df" - which is short for data frame
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

In [5]:
## when typing df and running, we bring up the table/csv file we named "df"
df

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [6]:
## this shows us the first five rows only (the head) - putting a number in the parenthesis (like 10) shows you the first _ rows
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [11]:
## this shows us the last five rows only - putting a number in the parenthesis, gives us the last _ rows
df.tail()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [12]:
# the .shape, shows us the size or shape of data, this shows us the number of rows and columns
df.shape

(11933, 11)

In [16]:
## this gives us the first value in our shape
df.shape[0]

11933

In [18]:
## adds texts to the df.shape[] function, giving it more meaning and allows other people to understand value better
print(f'the number of rows in our dataframe is {df.shape[0]} rows')
print(f'the number of coulumns in our dataframe is {df.shape[1]} rows')

the number of rows in our dataframe is 11933 rows
the number of coulumns in our dataframe is 11 rows

In [20]:
## this gives us the first five values of age
df['age'].head()

0    43.0
1    66.0
2    44.0
3     5.0
4     2.0
Name: age, dtype: float64

In [22]:
## we are having python tell us wether the math problem is right or wrong
1+1==2

True

In [23]:
## we are having python tell us wether the math problem is right or wrong
1+1==3

False

In [24]:
## we are having python tell us wether the math problem is right or wrong, but we assigned true to the integer 1 and false to the integer 0

int(1+1==2)

1

In [25]:
## we are having python tell us wether the math problem is right or wrong, but we assigned true to the integer 1 and false to the integer 0
int(1+1==3)

0

## Data Cleaning

In [26]:
## this is giving us the amount of missing variables for each column
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education          4139
bmi                3462
height_cm          3434
systolic_bp        4416
has_diabetes        193
hba1c              5218
fasting_glucose    8261
dtype: int64

In [27]:
## this is giving the percent of patients with the value missing for the specific variables
df.isna().mean() * 100

id                  0.000000
gender              0.000000
age                 0.000000
race_ethnicity      0.000000
education          34.685326
bmi                29.011984
height_cm          28.777340
systolic_bp        37.006620
has_diabetes        1.617364
hba1c              43.727478
fasting_glucose    69.228191
dtype: float64

In [29]:
## here we are getting rid of the rows that dont have data for wether the patient has diabetes or not - we are creating a new dataframe (df_clean) for this data removal/cleaning

df_clean = df.dropna(subset=['has_diabetes']).copy()

In [30]:
## here we are verifying wether our cleaning worked or not by reruning the percent average command

df_clean.isna().mean() * 100

id                  0.000000
gender              0.000000
age                 0.000000
race_ethnicity      0.000000
education          33.611584
bmi                27.844974
height_cm          27.606474
systolic_bp        35.971039
has_diabetes        0.000000
hba1c              42.802385
fasting_glucose    68.722317
dtype: float64

In [32]:
## here we are verifying that we have less rows, since we removed some with the clean
df_clean.shape

(11740, 11)

In [40]:
## here we are assigning the mean systolic blood pressure to : mean_bp , and having python give us the mean using the print function
mean_bp = df_clean['systolic_bp'].mean()
print(mean_bp)

119.28854596248502

In [41]:
## here we are filling any missing blood pressure values in our data with the mean


df_clean['systolic_bp'] = df_clean['systolic_bp'].fillna(mean_bp)

### Transform Variables

In [45]:
## here we are converting numerical values to categorical values
## using the cut function, we are basically converting the numerical bmi to weither their obese, under over or normal weight
df['bmi_category'] = pd.cut(df['bmi'],
                            bins=[0, 18.5, 25, 30, 100],
                            labels=['Underweight', 'Normal', 'Overweight', 'Obese'])

In [47]:
## here we are checking our work, and can see that we have successfully inserted the categorical data
df['bmi_category'].head()

0    Overweight
1         Obese
2    Overweight
3        Normal
4           NaN
Name: bmi_category, dtype: category
Categories (4, object): ['Underweight' < 'Normal' < 'Overweight' < 'Obese']

In [48]:
## Here we are given the number of patients in each BMI category
df['bmi_category'].value_counts()

bmi_category
Obese          2666
Normal         2400
Overweight     2189
Underweight    1216
Name: count, dtype: int64

###Categorical Variable Transformation

In [49]:
##here we are looking at the first five values for education, noting that it shows us the value in a number, which is less meaningful than if it was transformed into a categorical variable

df['education'].head()

0    5.0
1    5.0
2    3.0
3    NaN
4    NaN
Name: education, dtype: float64

In [56]:
## here we are assigning categories/words for each number in the education data set, this is making it more meaningful because college grad means more than "5"

education_map = {
    1: 'Less than 9th grade',
    2: '9-11th grade',
    3: 'High school grad',
    4: 'Some college or AA degree',
    5: 'College Graduate',
    9: 'Do not know',
    'nan': 'Missing'
}

In [59]:
## here we are checking are work and making sure 1 brings up the correct category we just set up
education_map[1]

'Less than 9th grade'

In [60]:
# here we created a new field by converting education from the map we created above,
# we then told the program to count the amount of people that fall in each category

df['education_label'] = df['education'].map(education_map)
df['education_label'].value_counts()

education_label
College Graduate             2625
Some college or AA degree    2370
High school grad             1749
9-11th grade                  666
Less than 9th grade           373
Do not know                    11
Name: count, dtype: int64

###**Data Summarization**

In [66]:
#numerical values
# here we are asking the program to figure out the mean of the age, and assigning it to the variable avg_age, and also having it round to the nearest tenth decimal point
# we also use format string literal to combine meaningful words with the rounded average age
avg_age = df['age'].mean()
print(round(avg_age,0))
print(f'The average age in our data is {round(avg_age,0)}')

38.0
The average age in our data is 38.0

In [70]:
# here we are having the program figure out the standard deviation for age, we then use format string literals to represent the sd meaningfully
std_age = df['age'].std()
print(f'The standard deviation for age in our data is {round(std_age,0)}')

The standard deviation for age in our data is 26.0

In [71]:
# here we are having the program figure out the median for us
df['age'].median()

37.0

In [73]:
# here we are having the program figure out the 25 and 75 quartile for us

df['age'].quantile([0.25, 0.75])

0.25    13.0
0.75    62.0
Name: age, dtype: float64

In [74]:
## here we are having the program figure out the most repeated value or "mode" for the age
df['age'].mode()

0    80.0
Name: age, dtype: float64

In [75]:
## gives us a comprehensive list of descriptors of the data
df['age'].describe()

count    1.193300e+04
mean     3.831786e+01
std      2.560199e+01
min      5.397605e-79
25%      1.300000e+01
50%      3.700000e+01
75%      6.200000e+01
max      8.000000e+01
Name: age, dtype: float64

# Summarizing Categorical Variables

In [77]:
##gives us the amount of males and females in the data -- gives us a frequency table
df['gender'].value_counts()

gender
2.0    6358
1.0    5575
Name: count, dtype: int64

In [79]:
## here we are showing how many people in each bmi category for each diabetes category
pd.crosstab(df['has_diabetes'], df['bmi_category'])

bmi_category  Underweight  Normal  Overweight  Obese
has_diabetes
1.0                     4     109         233    504
2.0                  1211    2251        1886   2042
3.0                     0      39          70    120
9.0                     1       1           0      0

In [80]:
## here we are creating a proportion of how many people in each diabetes category have what BMI category, equaling 100
pd.crosstab(df['has_diabetes'], df['bmi_category'], normalize='index') * 100

bmi_category  Underweight     Normal  Overweight      Obese
has_diabetes
1.0              0.470588  12.823529   27.411765  59.294118
2.0             16.387009  30.460081   25.520974  27.631935
3.0              0.000000  17.030568   30.567686  52.401747
9.0             50.000000  50.000000    0.000000   0.000000

In [81]:
#df.groupby('grouping_variable')['numeric_variable'].calculation()
#this is giving us the average bMI per each diabetes group
df.groupby('has_diabetes')['bmi'].mean()

has_diabetes
1.0    32.981412
2.0    26.439797
3.0    32.068559
9.0    19.250000
Name: bmi, dtype: float64